# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d5bb7bb5bd535702989999c074724e119ddb01960fb6dbc107c79a5e7c09bbf62ca77235de1066298ad1f6951f07d703e9d84444f996f8f0e197ac478e25b88

test:
  secret_key_base: d283df06566299b5feb02c44e5114a00b6545bc23d6ef6a43e0cf128966d128431975542b5e620d933f3febaf5143acb370b179ef085f758df5325df6ac709cc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
